### ISSUE TITLE
Add StructPartial function to allow for conditional validation

### ISSUE THREAD

**Issue by joeybloggs** [bluesuncorp/validator#149]
#### To Add
Add StructPartial function to allow for conditional validation. some people require contextual validation, this will give them the option to include or exclude fields on the struct for their needs.
```go
// exclude - will determine if the fields in map will be included or excluded, 
// whichever there are less of would make sense
// map Key will be the Field name and using struct{} as value to limit memory, 
// consumes less memory than bool.
function StructPartial(current interface{}, exclude bool, fields map[string]struct{}){
...
}
```

**Comment by jtriber** [comment]
Suggesting the following changes to make the behavior clear at the call level:

// keep this as a single function but make it private
structPartial(current interface{}, exclude bool, fields map[string]struct{}) ValidationErrors  {...}

// public interface
StructPartial(current interface{}, fields map[string]struct{}) ValidationErrors
StructExcept(current interface{}, fields map[string]struct{}) ValidationErrors

**Comment by joeybloggs** [comment]
closing this issue, but am still interested in help with documentation + examples.
