### ISSUE TITLE
Unable to get validator

### ISSUE THREAD

**Issue by gayanhewa** [bluesuncorp/validator#165]
This is what I get when I run go get , any idea what I am doing wrong ?
    
    # gopkg.in/bluesuncorp/validator.v7
    src/gopkg.in/bluesuncorp/validator.v7/validator.go:43: undefined: sync.Pool

**Comment by joeybloggs** [comment]
What version of Go are you using?

it sounds like you're using an older version of Go, I believe sync.Pool is only in go 1.3 and above

**Comment by gayanhewa** [comment]
Looks like it then. I am on 1.2.1 I will probably upgrade.
