### ISSUE TITLE
Error() prints too many end-lines

### ISSUE THREAD

**Issue by manucorporat** [bluesuncorp/validator#44]
Since the errors reported by validator will be likely sent through JSON or printed in a log:
I would recommend to remove most of the end-lines:

```
Struct: Field validation for "Id" failed on the "required" tag
```

instead of:
```
Struct:
Field validation for "Id" failed on the "required" tag


```

**Comment by joeybloggs** [comment]
I agree this makes sense for logging, I will remove the line breaks.

I do however feel the need to point out that, like the documentation states, these errors are intended for debugging and not production error messages.

For example the end user would probably want to see the error
>Email is required
Instead of
>Field validation for "Email" failed on the "required" tag

**Comment by manucorporat** [comment]
I am working in a complete integration with gin, this is a automatic generated error JSON.
```json
{  
   "error":"Struct:JSON\nField validation for \"Title\" failed on the \"required\" tag\nField validation for \"Description\" failed on the \"required\" tag\nField validation for \"Body\" failed on the \"required\" tag\n\n\n",
   "fields":[  
      "title",
      "description",
      "body"
   ],
   "message":"title, description and body are required."
}
```
see! there are many end-lines in the error message.

**Comment by joeybloggs** [comment]
I am working on this and a few other things and should be completed within the next few hours.

**Comment by manucorporat** [comment]
@joeybloggs nice! 
check out my work in progress, maybe we should join efforts (but for now... I am going to sleep ;) )
https://github.com/gin-gonic/validator/commit/474180a2dd22572102897e4db08c6fddbac5c767
https://github.com/gin-gonic/gin/commit/784d73477d056308e8c6ea666d52048906e48a7c

**Comment by manucorporat** [comment]
offtopic: I love the new v5 API. nice work!

**Comment by joeybloggs** [comment]
thanks @manucorporat 

I'll take a look

**Comment by manucorporat** [comment]
nice!
