### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by pavlik** [bluesuncorp/validator#48]
I want to use [Sourcegraph](https://sourcegraph.com) for validator code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/bluesuncorp/validator. (It should only take 30 seconds.)

Thank you!

**Comment by joeybloggs** [comment]
OK I believe this is all setup now.

If you could please confirm, then I'll close this issue.

**Comment by pavlik** [comment]
Confirm! Working.

**Comment by joeybloggs** [comment]
@pavlik thanks for the interest!
